name: Terrascan Scan

on:
  push: # on everycommit on master
    branches:
      - master
  pull_request: #on every pull request to master
    branches:
      - master
  workflow_dispatch: # to trigger manually 

jobs:
  terrascan: # Job name
    name: Terrascan Security Scan
    runs-on: ubuntu-latest # runner name (here it is self hosted runner)

    steps:
      - name: Checkout Repository  #  cloning the repo
        uses: actions/checkout@v4

      - name: Install Terrascan & terraform
        run: |
          # Terrascan install
          sudo apt-get update && sudo apt-get install -y jq
          TERRASCAN_URL=$(curl -s https://api.github.com/repos/tenable/terrascan/releases/latest | jq -r '.assets[] | select(.name | contains("Linux_x86_64.tar.gz")) | .browser_download_url')
          curl -L "$TERRASCAN_URL" -o terrascan.tar.gz
          tar -xf terrascan.tar.gz terrascan && rm terrascan.tar.gz
          sudo install terrascan /usr/local/bin && rm terrascan

      - name: Verify Terrascan Installation
        run: |
          terrascan version

      # - name: Connectivity Tests
      #   run: |
      #     curl -s https://api.github.com/rate_limit | jq
      #     sleep 1
      #     echo "HashiCorp TLS version check"
      #     curl -v https://registry.terraform.io/v1/providers/hashicorp/tls/versions

      - name: Terraform installation
        run: |
          export TF_LOG=DEBUG
          export TERRASCAN_LOG_LEVEL=debug
          sudo apt update && sudo apt install -y wget unzip
          # Add HashiCorp repository without prompt
          sudo rm -f /usr/share/keyrings/hashicorp-archive-keyring.gpg  # Delete existing file
          wget -q -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update
          # installing tf version 1.5.0
          sudo apt install -y terraform=1.5.0-1
          # Terraform version check
          terraform -v
          # Set Terraform plugin cache
          mkdir -p ~/.terraform.d/plugin-cache
          export TF_PLUGIN_CACHE_DIR="$HOME/.terraform.d/plugin-cache"
      
      - name: Run Terrascan Scan and Save Report
        run: |
           # Force Terraform to retry provider download
           cd Jenkins-installation
           echo "terraform init with retries"
           for i in {1..3}; do terraform init && break || sleep 5; done

           # Run Terrascan
           terrascan init
           #terrascan scan -d . -o json > terrascan-report.json
           terrascan scan -d .
        continue-on-error: true

      - name: Upload Terrascan Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terrascan-report
          path: ./Jenkins-installation/terrascan-report.json
          retention-days: 5
        
        


