name: Terrascan Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  terrascan:
    name: Terrascan Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        # with:
        #   token: ${{ secrets.PAT_TOKEN }}

      - name: Install Terrascan
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          sudo curl -L "$(curl -s https://api.github.com/repos/tenable/terrascan/releases/latest | grep -o -E "https://.+?_Linux_x86_64.tar.gz")" > terrascan.tar.gz
          sudo tar -xf terrascan.tar.gz terrascan && rm terrascan.tar.gz
          sudo install terrascan /usr/local/bin && rm terrascan
          # TERRASCAN_URL=$(curl -s https://api.github.com/repos/tenable/terrascan/releases/latest | jq -r '.assets[] | select(.name | contains("linux_amd64")) | .browser_download_url')
          # curl -L "$TERRASCAN_URL" -o terrascan
          # chmod +x terrascan
          # sudo mv terrascan /usr/local/bin/

      - name: terrascanversion
        run: |
          terrascan version

      - name: Run Terrascan Scan and Save Report
        run: |
          export TF_LOG=DEBUG
          export TERRASCAN_LOG_LEVEL=debug
          sudo apt update && sudo apt install -y wget
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update
          sudo apt install terraform=1.5.0-1
          terraform -v
          terrascan scan -d ./Jenkins-installation -o json > terrascan-report.json

      - name: Upload Terrascan Report as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terrascan-report
          path: terrascan-report.json
          retention-days: 5
